### ISSUE TITLE
Websocket Authorization

### ISSUE THREAD

**Issue by holesch** [almarklein/asgineer#39]
I'd like to do authorization in a websocket handler before accepting the connection. For example:

```python
async def websocket_handler(request):
    if not is_authorized(request):
        return 401, {"WWW-Authenticate": "Basic"}, "Invalid credentials"

    await request.accept()
```

I expected it to send the HTTP response, but instead it raised the following exception:
```
OSError: A websocket handler should return None; use request.send() and request.receive() to communicate.
```

**Comment by almarklein** [comment]
It's been a while since I looked into the low-level details of websockets, but I don't think you can simply return a plain result. We could add a `request.deny()` though, or something along that line. Have you looked at other related libs do/support this?

**Comment by holesch** [comment]
As long as you don't accept the connection, it's still just an HTTP request, so you can send an HTTP response with a plain text error message. `websockets` actually has such a method as you suggested: [`ServerConnection.reject()`](https://websockets.readthedocs.io/en/stable/reference/server.html#websockets.server.ServerConnection.reject).

I thought about subclassing `HttpRequest`, instead of `BaseRequest`, but that's probably overkill.

So `.deny()`/`.reject()` sounds good to me. Let me know if I should work on it. I might find some time next week.

**Comment by holesch** [comment]
So I looked into it a bit more: Since asgineer uses the ASGI abstraction, it's not as easy as just sending an HTTP response (I should've thought about that).

Here's what's possible with ASGI using the [`websocket.close` message](https://asgi.readthedocs.io/en/latest/specs/www.html#close-send-event):
> If this is sent before the socket is accepted, the server must close the connection with a HTTP 403 error code (Forbidden), and not complete the WebSocket handshake; [...]

Changing the HTTP status code is not possible, but there's the [Websocket Denial Response ASGI extension](https://asgi.readthedocs.io/en/latest/extensions.html#websocket-denial-response) for that. It also states the reason why this is just an extension:
> Rather than being a core part of ASGI, this is an extension for what is considered a niche feature as most clients do not utilise the denial response.

Uvicorn doesn't support this extension and it hasn't been decided if it ever will support it. A [discussion for adding Websocket Denial Response to Uvicorn](https://github.com/encode/uvicorn/discussions/1805) was started.

Regarding my specific issue: I'm fine with using `request.close()` and sending the 403, even if it's not the "correct" one.

**Comment by almarklein** [comment]
Thanks for the detailed feedback! Yeah, being able to deny the connection in a more appropriate way would have been nice ...
